//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebServices.AccountManagementReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AccountManagement_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement")]
    public partial class AccountManagement : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeleteCautionRefundLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmployeeLeaveDeclineOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmployeeLeaveForwardtogovtOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmployeeLeaveSanctionOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmployeeLeaveSubmitOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostTransferAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostedCautionMoneyReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetStudentFeeEntryNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentFeeCollectionPostingOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubMitCautionMoneyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnpostedCautionMoneyReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AccountManagement() {
            this.Url = global::WebServices.Properties.Settings.Default.WebServices_AccountManagementReference_AccountManagement;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteCautionRefundLineCompletedEventHandler DeleteCautionRefundLineCompleted;
        
        /// <remarks/>
        public event EmployeeLeaveDeclineCompletedEventHandler EmployeeLeaveDeclineCompleted;
        
        /// <remarks/>
        public event EmployeeLeaveForwardtogovtCompletedEventHandler EmployeeLeaveForwardtogovtCompleted;
        
        /// <remarks/>
        public event EmployeeLeaveSanctionCompletedEventHandler EmployeeLeaveSanctionCompleted;
        
        /// <remarks/>
        public event EmployeeLeaveSubmitCompletedEventHandler EmployeeLeaveSubmitCompleted;
        
        /// <remarks/>
        public event GetLinesCompletedEventHandler GetLinesCompleted;
        
        /// <remarks/>
        public event PostTransferAccountCompletedEventHandler PostTransferAccountCompleted;
        
        /// <remarks/>
        public event PostedCautionMoneyReportCompletedEventHandler PostedCautionMoneyReportCompleted;
        
        /// <remarks/>
        public event SetStudentFeeEntryNoCompletedEventHandler SetStudentFeeEntryNoCompleted;
        
        /// <remarks/>
        public event StudentFeeCollectionPostingCompletedEventHandler StudentFeeCollectionPostingCompleted;
        
        /// <remarks/>
        public event SubMitCautionMoneyCompletedEventHandler SubMitCautionMoneyCompleted;
        
        /// <remarks/>
        public event UnpostedCautionMoneyReportCompletedEventHandler UnpostedCautionMoneyReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/AccountManagement:DeleteCautionRefundLine" +
            "", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", ResponseElementName="DeleteCautionRefundLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool DeleteCautionRefundLine(string refundSlNo, int lineNo) {
            object[] results = this.Invoke("DeleteCautionRefundLine", new object[] {
                        refundSlNo,
                        lineNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteCautionRefundLineAsync(string refundSlNo, int lineNo) {
            this.DeleteCautionRefundLineAsync(refundSlNo, lineNo, null);
        }
        
        /// <remarks/>
        public void DeleteCautionRefundLineAsync(string refundSlNo, int lineNo, object userState) {
            if ((this.DeleteCautionRefundLineOperationCompleted == null)) {
                this.DeleteCautionRefundLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCautionRefundLineOperationCompleted);
            }
            this.InvokeAsync("DeleteCautionRefundLine", new object[] {
                        refundSlNo,
                        lineNo}, this.DeleteCautionRefundLineOperationCompleted, userState);
        }
        
        private void OnDeleteCautionRefundLineOperationCompleted(object arg) {
            if ((this.DeleteCautionRefundLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCautionRefundLineCompleted(this, new DeleteCautionRefundLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/AccountManagement:EmployeeLeaveDecline", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", ResponseElementName="EmployeeLeaveDecline_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EmployeeLeaveDecline(int entryNo) {
            this.Invoke("EmployeeLeaveDecline", new object[] {
                        entryNo});
        }
        
        /// <remarks/>
        public void EmployeeLeaveDeclineAsync(int entryNo) {
            this.EmployeeLeaveDeclineAsync(entryNo, null);
        }
        
        /// <remarks/>
        public void EmployeeLeaveDeclineAsync(int entryNo, object userState) {
            if ((this.EmployeeLeaveDeclineOperationCompleted == null)) {
                this.EmployeeLeaveDeclineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmployeeLeaveDeclineOperationCompleted);
            }
            this.InvokeAsync("EmployeeLeaveDecline", new object[] {
                        entryNo}, this.EmployeeLeaveDeclineOperationCompleted, userState);
        }
        
        private void OnEmployeeLeaveDeclineOperationCompleted(object arg) {
            if ((this.EmployeeLeaveDeclineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmployeeLeaveDeclineCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/AccountManagement:EmployeeLeaveForwardtog" +
            "ovt", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", ResponseElementName="EmployeeLeaveForwardtogovt_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EmployeeLeaveForwardtogovt(int entryNo) {
            this.Invoke("EmployeeLeaveForwardtogovt", new object[] {
                        entryNo});
        }
        
        /// <remarks/>
        public void EmployeeLeaveForwardtogovtAsync(int entryNo) {
            this.EmployeeLeaveForwardtogovtAsync(entryNo, null);
        }
        
        /// <remarks/>
        public void EmployeeLeaveForwardtogovtAsync(int entryNo, object userState) {
            if ((this.EmployeeLeaveForwardtogovtOperationCompleted == null)) {
                this.EmployeeLeaveForwardtogovtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmployeeLeaveForwardtogovtOperationCompleted);
            }
            this.InvokeAsync("EmployeeLeaveForwardtogovt", new object[] {
                        entryNo}, this.EmployeeLeaveForwardtogovtOperationCompleted, userState);
        }
        
        private void OnEmployeeLeaveForwardtogovtOperationCompleted(object arg) {
            if ((this.EmployeeLeaveForwardtogovtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmployeeLeaveForwardtogovtCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/AccountManagement:EmployeeLeaveSanction", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", ResponseElementName="EmployeeLeaveSanction_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EmployeeLeaveSanction(int entryNo) {
            this.Invoke("EmployeeLeaveSanction", new object[] {
                        entryNo});
        }
        
        /// <remarks/>
        public void EmployeeLeaveSanctionAsync(int entryNo) {
            this.EmployeeLeaveSanctionAsync(entryNo, null);
        }
        
        /// <remarks/>
        public void EmployeeLeaveSanctionAsync(int entryNo, object userState) {
            if ((this.EmployeeLeaveSanctionOperationCompleted == null)) {
                this.EmployeeLeaveSanctionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmployeeLeaveSanctionOperationCompleted);
            }
            this.InvokeAsync("EmployeeLeaveSanction", new object[] {
                        entryNo}, this.EmployeeLeaveSanctionOperationCompleted, userState);
        }
        
        private void OnEmployeeLeaveSanctionOperationCompleted(object arg) {
            if ((this.EmployeeLeaveSanctionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmployeeLeaveSanctionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/AccountManagement:EmployeeLeaveSubmit", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", ResponseElementName="EmployeeLeaveSubmit_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EmployeeLeaveSubmit(string hRMSID, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime fromDate, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime toDate, int typeofLeave) {
            this.Invoke("EmployeeLeaveSubmit", new object[] {
                        hRMSID,
                        fromDate,
                        toDate,
                        typeofLeave});
        }
        
        /// <remarks/>
        public void EmployeeLeaveSubmitAsync(string hRMSID, System.DateTime fromDate, System.DateTime toDate, int typeofLeave) {
            this.EmployeeLeaveSubmitAsync(hRMSID, fromDate, toDate, typeofLeave, null);
        }
        
        /// <remarks/>
        public void EmployeeLeaveSubmitAsync(string hRMSID, System.DateTime fromDate, System.DateTime toDate, int typeofLeave, object userState) {
            if ((this.EmployeeLeaveSubmitOperationCompleted == null)) {
                this.EmployeeLeaveSubmitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmployeeLeaveSubmitOperationCompleted);
            }
            this.InvokeAsync("EmployeeLeaveSubmit", new object[] {
                        hRMSID,
                        fromDate,
                        toDate,
                        typeofLeave}, this.EmployeeLeaveSubmitOperationCompleted, userState);
        }
        
        private void OnEmployeeLeaveSubmitOperationCompleted(object arg) {
            if ((this.EmployeeLeaveSubmitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmployeeLeaveSubmitCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/AccountManagement:GetLines", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", ResponseElementName="GetLines_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetLines(string academicYear, string refundSlNo) {
            this.Invoke("GetLines", new object[] {
                        academicYear,
                        refundSlNo});
        }
        
        /// <remarks/>
        public void GetLinesAsync(string academicYear, string refundSlNo) {
            this.GetLinesAsync(academicYear, refundSlNo, null);
        }
        
        /// <remarks/>
        public void GetLinesAsync(string academicYear, string refundSlNo, object userState) {
            if ((this.GetLinesOperationCompleted == null)) {
                this.GetLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLinesOperationCompleted);
            }
            this.InvokeAsync("GetLines", new object[] {
                        academicYear,
                        refundSlNo}, this.GetLinesOperationCompleted, userState);
        }
        
        private void OnGetLinesOperationCompleted(object arg) {
            if ((this.GetLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLinesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/AccountManagement:PostTransferAccount", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", ResponseElementName="PostTransferAccount_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PostTransferAccount(string entryNo) {
            this.Invoke("PostTransferAccount", new object[] {
                        entryNo});
        }
        
        /// <remarks/>
        public void PostTransferAccountAsync(string entryNo) {
            this.PostTransferAccountAsync(entryNo, null);
        }
        
        /// <remarks/>
        public void PostTransferAccountAsync(string entryNo, object userState) {
            if ((this.PostTransferAccountOperationCompleted == null)) {
                this.PostTransferAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostTransferAccountOperationCompleted);
            }
            this.InvokeAsync("PostTransferAccount", new object[] {
                        entryNo}, this.PostTransferAccountOperationCompleted, userState);
        }
        
        private void OnPostTransferAccountOperationCompleted(object arg) {
            if ((this.PostTransferAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostTransferAccountCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/AccountManagement:PostedCautionMoneyRepor" +
            "t", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", ResponseElementName="PostedCautionMoneyReport_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string PostedCautionMoneyReport(string refundSlNo) {
            object[] results = this.Invoke("PostedCautionMoneyReport", new object[] {
                        refundSlNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostedCautionMoneyReportAsync(string refundSlNo) {
            this.PostedCautionMoneyReportAsync(refundSlNo, null);
        }
        
        /// <remarks/>
        public void PostedCautionMoneyReportAsync(string refundSlNo, object userState) {
            if ((this.PostedCautionMoneyReportOperationCompleted == null)) {
                this.PostedCautionMoneyReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostedCautionMoneyReportOperationCompleted);
            }
            this.InvokeAsync("PostedCautionMoneyReport", new object[] {
                        refundSlNo}, this.PostedCautionMoneyReportOperationCompleted, userState);
        }
        
        private void OnPostedCautionMoneyReportOperationCompleted(object arg) {
            if ((this.PostedCautionMoneyReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostedCautionMoneyReportCompleted(this, new PostedCautionMoneyReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/AccountManagement:SetStudentFeeEntryNo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", ResponseElementName="SetStudentFeeEntryNo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetStudentFeeEntryNo(string entryNo) {
            this.Invoke("SetStudentFeeEntryNo", new object[] {
                        entryNo});
        }
        
        /// <remarks/>
        public void SetStudentFeeEntryNoAsync(string entryNo) {
            this.SetStudentFeeEntryNoAsync(entryNo, null);
        }
        
        /// <remarks/>
        public void SetStudentFeeEntryNoAsync(string entryNo, object userState) {
            if ((this.SetStudentFeeEntryNoOperationCompleted == null)) {
                this.SetStudentFeeEntryNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetStudentFeeEntryNoOperationCompleted);
            }
            this.InvokeAsync("SetStudentFeeEntryNo", new object[] {
                        entryNo}, this.SetStudentFeeEntryNoOperationCompleted, userState);
        }
        
        private void OnSetStudentFeeEntryNoOperationCompleted(object arg) {
            if ((this.SetStudentFeeEntryNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetStudentFeeEntryNoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/AccountManagement:StudentFeeCollectionPos" +
            "ting", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", ResponseElementName="StudentFeeCollectionPosting_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StudentFeeCollectionPosting(string entryNo) {
            this.Invoke("StudentFeeCollectionPosting", new object[] {
                        entryNo});
        }
        
        /// <remarks/>
        public void StudentFeeCollectionPostingAsync(string entryNo) {
            this.StudentFeeCollectionPostingAsync(entryNo, null);
        }
        
        /// <remarks/>
        public void StudentFeeCollectionPostingAsync(string entryNo, object userState) {
            if ((this.StudentFeeCollectionPostingOperationCompleted == null)) {
                this.StudentFeeCollectionPostingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentFeeCollectionPostingOperationCompleted);
            }
            this.InvokeAsync("StudentFeeCollectionPosting", new object[] {
                        entryNo}, this.StudentFeeCollectionPostingOperationCompleted, userState);
        }
        
        private void OnStudentFeeCollectionPostingOperationCompleted(object arg) {
            if ((this.StudentFeeCollectionPostingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentFeeCollectionPostingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/AccountManagement:SubMitCautionMoney", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", ResponseElementName="SubMitCautionMoney_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SubMitCautionMoney(string studentNo, string academicYear) {
            this.Invoke("SubMitCautionMoney", new object[] {
                        studentNo,
                        academicYear});
        }
        
        /// <remarks/>
        public void SubMitCautionMoneyAsync(string studentNo, string academicYear) {
            this.SubMitCautionMoneyAsync(studentNo, academicYear, null);
        }
        
        /// <remarks/>
        public void SubMitCautionMoneyAsync(string studentNo, string academicYear, object userState) {
            if ((this.SubMitCautionMoneyOperationCompleted == null)) {
                this.SubMitCautionMoneyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubMitCautionMoneyOperationCompleted);
            }
            this.InvokeAsync("SubMitCautionMoney", new object[] {
                        studentNo,
                        academicYear}, this.SubMitCautionMoneyOperationCompleted, userState);
        }
        
        private void OnSubMitCautionMoneyOperationCompleted(object arg) {
            if ((this.SubMitCautionMoneyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubMitCautionMoneyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/AccountManagement:UnpostedCautionMoneyRep" +
            "ort", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", ResponseElementName="UnpostedCautionMoneyReport_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/AccountManagement", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string UnpostedCautionMoneyReport(string refundSlNo) {
            object[] results = this.Invoke("UnpostedCautionMoneyReport", new object[] {
                        refundSlNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UnpostedCautionMoneyReportAsync(string refundSlNo) {
            this.UnpostedCautionMoneyReportAsync(refundSlNo, null);
        }
        
        /// <remarks/>
        public void UnpostedCautionMoneyReportAsync(string refundSlNo, object userState) {
            if ((this.UnpostedCautionMoneyReportOperationCompleted == null)) {
                this.UnpostedCautionMoneyReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnpostedCautionMoneyReportOperationCompleted);
            }
            this.InvokeAsync("UnpostedCautionMoneyReport", new object[] {
                        refundSlNo}, this.UnpostedCautionMoneyReportOperationCompleted, userState);
        }
        
        private void OnUnpostedCautionMoneyReportOperationCompleted(object arg) {
            if ((this.UnpostedCautionMoneyReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnpostedCautionMoneyReportCompleted(this, new UnpostedCautionMoneyReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DeleteCautionRefundLineCompletedEventHandler(object sender, DeleteCautionRefundLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCautionRefundLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCautionRefundLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void EmployeeLeaveDeclineCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void EmployeeLeaveForwardtogovtCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void EmployeeLeaveSanctionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void EmployeeLeaveSubmitCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetLinesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PostTransferAccountCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PostedCautionMoneyReportCompletedEventHandler(object sender, PostedCautionMoneyReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostedCautionMoneyReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostedCautionMoneyReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SetStudentFeeEntryNoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void StudentFeeCollectionPostingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SubMitCautionMoneyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UnpostedCautionMoneyReportCompletedEventHandler(object sender, UnpostedCautionMoneyReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnpostedCautionMoneyReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnpostedCautionMoneyReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591