//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/EmployeeAd" +
            "ditionalInfoCard")]
        public string WebServices_EmployeeAdditionalCardReference_EmployeeAdditionalInfoCard_Service {
            get {
                return ((string)(this["WebServices_EmployeeAdditionalCardReference_EmployeeAdditionalInfoCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/EmployeeCard")]
        public string WebServices_EmplaoyeeReference_EmployeeCard_Service {
            get {
                return ((string)(this["WebServices_EmplaoyeeReference_EmployeeCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/FinancialU" +
            "pgradeCard")]
        public string WebServices_FinancialUpgradeReference_FinancialUpgradeCard_Service {
            get {
                return ((string)(this["WebServices_FinancialUpgradeReference_FinancialUpgradeCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/EmployeePr" +
            "omotionHistoryCard")]
        public string WebServices_EmployeePromotionHistoryReference_EmployeePromotionHistoryCard_Service {
            get {
                return ((string)(this["WebServices_EmployeePromotionHistoryReference_EmployeePromotionHistoryCard_Servic" +
                    "e"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/EmployeeTransfe" +
            "rApplicationCard")]
        public string WebServices_EmployeeTransferApplicationReference_EmployeeTransferApplicationCard_Service {
            get {
                return ((string)(this["WebServices_EmployeeTransferApplicationReference_EmployeeTransferApplicationCard_" +
                    "Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/EmployeeAc" +
            "hvCard")]
        public string WebServices_EmployeeAchvReference_EmployeeAchvCard_Service {
            get {
                return ((string)(this["WebServices_EmployeeAchvReference_EmployeeAchvCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/EmployeeDscpCar" +
            "d")]
        public string WebServices_EmployeeDscpReference_EmployeeDscpCard_Service {
            get {
                return ((string)(this["WebServices_EmployeeDscpReference_EmployeeDscpCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/EmployeeTrainin" +
            "gHistoryCard")]
        public string WebServices_EmployeeTrainingHistoryReference_EmployeeTrainingHistoryCard_Service {
            get {
                return ((string)(this["WebServices_EmployeeTrainingHistoryReference_EmployeeTrainingHistoryCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/AnnualPerf" +
            "ormanceCard")]
        public string WebServices_AnnualPerformanceReference_AnnualPerformanceCard_Service {
            get {
                return ((string)(this["WebServices_AnnualPerformanceReference_AnnualPerformanceCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/CourtCaseC" +
            "ard")]
        public string WebServices_CourtCaseReference_CourtCaseCard_Service {
            get {
                return ((string)(this["WebServices_CourtCaseReference_CourtCaseCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/RTIMonitor" +
            "ingCard")]
        public string WebServices_RTIMonitoringReference_RTIMonitoringCard_Service {
            get {
                return ((string)(this["WebServices_RTIMonitoringReference_RTIMonitoringCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/AnnualEsta" +
            "blishmentReviewCard")]
        public string WebServices_AnnualEstablishmentReviewReference_AnnualEstablishmentReviewCard_Service {
            get {
                return ((string)(this["WebServices_AnnualEstablishmentReviewReference_AnnualEstablishmentReviewCard_Serv" +
                    "ice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Codeunit/HRMSCo" +
            "deunit")]
        public string WebServices_HRMSCodeunitReference_HRMSCodeunit {
            get {
                return ((string)(this["WebServices_HRMSCodeunitReference_HRMSCodeunit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/EmployeeTr" +
            "ansferHistoryCard")]
        public string WebServices_EmployeeTransferHistoryReference_EmployeeTransferHistoryCard_Service {
            get {
                return ((string)(this["WebServices_EmployeeTransferHistoryReference_EmployeeTransferHistoryCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Codeunit/InfraCodeun" +
            "it")]
        public string WebServices_InfraCodeunitReference_InfraCodeunit {
            get {
                return ((string)(this["WebServices_InfraCodeunitReference_InfraCodeunit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/CourseFeeH" +
            "eaderCard")]
        public string WebServices_CourseFeeHeaderReference_CourseFeeHeaderCard_Service {
            get {
                return ((string)(this["WebServices_CourseFeeHeaderReference_CourseFeeHeaderCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/BookCard")]
        public string WebServices_BookCardReference_BookCard_Service {
            get {
                return ((string)(this["WebServices_BookCardReference_BookCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Codeunit/FeeMan" +
            "agementCodeUnit")]
        public string WebServices_FeeManagementCodeUnitReference2_FeeManagementCodeUnit {
            get {
                return ((string)(this["WebServices_FeeManagementCodeUnitReference2_FeeManagementCodeUnit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/LandCard")]
        public string WebServices_InfraLandCardReference_LandCard_Service {
            get {
                return ((string)(this["WebServices_InfraLandCardReference_LandCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/GeneralLandBuil" +
            "dingCard")]
        public string WebServices_InfraGeneralLandBuildingReference_GeneralLandBuildingCard_Service {
            get {
                return ((string)(this["WebServices_InfraGeneralLandBuildingReference_GeneralLandBuildingCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/InstituteBuildi" +
            "ngCard")]
        public string WebServices_InfraInstituteBuildingReference_InstituteBuildingCard_Service {
            get {
                return ((string)(this["WebServices_InfraInstituteBuildingReference_InstituteBuildingCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/HostelBuildingC" +
            "ard")]
        public string WebServices_InfraHostelBuildingReference_HostelBuildingCard_Service {
            get {
                return ((string)(this["WebServices_InfraHostelBuildingReference_HostelBuildingCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/StaffQuarterCar" +
            "d")]
        public string WebServices_InfraStaffQuarterReference_StaffQuarterCard_Service {
            get {
                return ((string)(this["WebServices_InfraStaffQuarterReference_StaffQuarterCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/AuditoriumBuild" +
            "ing")]
        public string WebServices_InfraAuditoriumBuildingReference_AuditoriumBuilding_Service {
            get {
                return ((string)(this["WebServices_InfraAuditoriumBuildingReference_AuditoriumBuilding_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/Newprojectcard")]
        public string WebServices_InfraNewprojectReference_Newprojectcard_Service {
            get {
                return ((string)(this["WebServices_InfraNewprojectReference_Newprojectcard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/Ongoingprojectc" +
            "ard")]
        public string WebServices_InfraOngoingprojectReference_Ongoingprojectcard_Service {
            get {
                return ((string)(this["WebServices_InfraOngoingprojectReference_Ongoingprojectcard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/Improvementproj" +
            "ectcard")]
        public string WebServices_InfraImprovementprojectReference_Improvementprojectcard_Service {
            get {
                return ((string)(this["WebServices_InfraImprovementprojectReference_Improvementprojectcard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/Projectprogress" +
            "detailscard")]
        public string WebServices_InfraProjectprogressdetailsReference_Projectprogressdetailscard_Service {
            get {
                return ((string)(this["WebServices_InfraProjectprogressdetailsReference_Projectprogressdetailscard_Servi" +
                    "ce"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/EstimatePrepCar" +
            "d")]
        public string WebServices_InfraEstimatePrepReference_EstimatePrepCard_Service {
            get {
                return ((string)(this["WebServices_InfraEstimatePrepReference_EstimatePrepCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/ServiceCard")]
        public string WebServices_InfraServiceReference_ServiceCard_Service {
            get {
                return ((string)(this["WebServices_InfraServiceReference_ServiceCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/BookCard")]
        public string WebServices_BookCardReference1_BookCard_Service {
            get {
                return ((string)(this["WebServices_BookCardReference1_BookCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/BookIssueC" +
            "ard")]
        public string WebServices_BookIssueCardReference_BookIssueCard_Service {
            get {
                return ((string)(this["WebServices_BookIssueCardReference_BookIssueCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Codeunit/LibraryMgmt" +
            "")]
        public string WebServices_LibraryMgmtReference_LibraryMgmt {
            get {
                return ((string)(this["WebServices_LibraryMgmtReference_LibraryMgmt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/CourseFeeH" +
            "eaderCard")]
        public string WebServices_CourseFeeHeaderReference1_CourseFeeHeaderCard_Service {
            get {
                return ((string)(this["WebServices_CourseFeeHeaderReference1_CourseFeeHeaderCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/CRONUS%20India%20Ltd./Page/AMCCard")]
        public string WebServices_InfraAMCReference_AMCCard_Service {
            get {
                return ((string)(this["WebServices_InfraAMCReference_AMCCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/GeneralPay" +
            "ment")]
        public string WebServices_FeeGeneralPaymentReference_GeneralPayment_Service {
            get {
                return ((string)(this["WebServices_FeeGeneralPaymentReference_GeneralPayment_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/BookAccess" +
            "ionCard")]
        public string WebServices_BookAccessionReference_BookAccessionCard_Service {
            get {
                return ((string)(this["WebServices_BookAccessionReference_BookAccessionCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Codeunit/Accoun" +
            "tManagement")]
        public string WebServices_AccountManagementReference_AccountManagement {
            get {
                return ((string)(this["WebServices_AccountManagementReference_AccountManagement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/CautionRef" +
            "undOrder")]
        public string WebServices_CautionRefundOrderReference_CautionRefundOrder_Service {
            get {
                return ((string)(this["WebServices_CautionRefundOrderReference_CautionRefundOrder_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Codeunit/Portal" +
            "Function")]
        public string WebServices_PortalFunctionReference_PortalFunction {
            get {
                return ((string)(this["WebServices_PortalFunctionReference_PortalFunction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/CautionRef" +
            "undSubformCard")]
        public string WebServices_CautionRefundSubformCardReference_CautionRefundSubformCard_Service {
            get {
                return ((string)(this["WebServices_CautionRefundSubformCardReference_CautionRefundSubformCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/FeeCollect" +
            "ion")]
        public string WebServices_StudentFeeCollectionReference_FeeCollection_Service {
            get {
                return ((string)(this["WebServices_StudentFeeCollectionReference_FeeCollection_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/DTE%2526T%252C%20Odisha/Page/UserAuthentic" +
            "ationCard")]
        public string WebServices_UserAuthenticationCardReference_UserAuthenticationCard_Service {
            get {
                return ((string)(this["WebServices_UserAuthenticationCardReference_UserAuthenticationCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Codeunit/Librar" +
            "yCodeunit")]
        public string WebServices_LibraryCodeunitReference_LibraryCodeunit {
            get {
                return ((string)(this["WebServices_LibraryCodeunitReference_LibraryCodeunit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/StudentFee" +
            "CollectionCard")]
        public string WebServices_StudentFeeCollectionCardReference_StudentFeeCollectionCard_Service {
            get {
                return ((string)(this["WebServices_StudentFeeCollectionCardReference_StudentFeeCollectionCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.252:10102/DTETDLVP/WS/GOVT%20POLYTECHNIC%20ANGUL/Page/TransferAc" +
            "count")]
        public string WebServices_TransferAccountReference_TransferAccount_Service {
            get {
                return ((string)(this["WebServices_TransferAccountReference_TransferAccount_Service"]));
            }
        }
    }
}
