//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebServices.FeeManagementCodeUnitReference2 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FeeManagementCodeUnit_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit")]
    public partial class FeeManagementCodeUnit : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgingReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback BankBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback CashBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerTrialBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback DayBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback FeeDemandOperationCompleted;
        
        private System.Threading.SendOrPostCallback FeeGenerationOperationCompleted;
        
        private System.Threading.SendOrPostCallback MoneyReceiptOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostCautionRefundOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostGeneralPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostStudentFeeCollectionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FeeManagementCodeUnit() {
            this.Url = global::WebServices.Properties.Settings.Default.WebServices_FeeManagementCodeUnitReference2_FeeManagementCodeUnit;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AgingReportCompletedEventHandler AgingReportCompleted;
        
        /// <remarks/>
        public event BankBookCompletedEventHandler BankBookCompleted;
        
        /// <remarks/>
        public event CashBookCompletedEventHandler CashBookCompleted;
        
        /// <remarks/>
        public event CustomerStatementCompletedEventHandler CustomerStatementCompleted;
        
        /// <remarks/>
        public event CustomerTrialBalanceCompletedEventHandler CustomerTrialBalanceCompleted;
        
        /// <remarks/>
        public event DayBookCompletedEventHandler DayBookCompleted;
        
        /// <remarks/>
        public event FeeDemandCompletedEventHandler FeeDemandCompleted;
        
        /// <remarks/>
        public event FeeGenerationCompletedEventHandler FeeGenerationCompleted;
        
        /// <remarks/>
        public event MoneyReceiptCompletedEventHandler MoneyReceiptCompleted;
        
        /// <remarks/>
        public event PostCautionRefundOrderCompletedEventHandler PostCautionRefundOrderCompleted;
        
        /// <remarks/>
        public event PostGeneralPaymentCompletedEventHandler PostGeneralPaymentCompleted;
        
        /// <remarks/>
        public event PostStudentFeeCollectionCompletedEventHandler PostStudentFeeCollectionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit:AgingReport", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", ResponseElementName="AgingReport_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string AgingReport(string customerNo1, string endDate1, int agingBy1, string periodLegth1, bool printAmtInLCY1, bool printDetails1, int headingType1, bool newPagePerCustomer1) {
            object[] results = this.Invoke("AgingReport", new object[] {
                        customerNo1,
                        endDate1,
                        agingBy1,
                        periodLegth1,
                        printAmtInLCY1,
                        printDetails1,
                        headingType1,
                        newPagePerCustomer1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AgingReportAsync(string customerNo1, string endDate1, int agingBy1, string periodLegth1, bool printAmtInLCY1, bool printDetails1, int headingType1, bool newPagePerCustomer1) {
            this.AgingReportAsync(customerNo1, endDate1, agingBy1, periodLegth1, printAmtInLCY1, printDetails1, headingType1, newPagePerCustomer1, null);
        }
        
        /// <remarks/>
        public void AgingReportAsync(string customerNo1, string endDate1, int agingBy1, string periodLegth1, bool printAmtInLCY1, bool printDetails1, int headingType1, bool newPagePerCustomer1, object userState) {
            if ((this.AgingReportOperationCompleted == null)) {
                this.AgingReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgingReportOperationCompleted);
            }
            this.InvokeAsync("AgingReport", new object[] {
                        customerNo1,
                        endDate1,
                        agingBy1,
                        periodLegth1,
                        printAmtInLCY1,
                        printDetails1,
                        headingType1,
                        newPagePerCustomer1}, this.AgingReportOperationCompleted, userState);
        }
        
        private void OnAgingReportOperationCompleted(object arg) {
            if ((this.AgingReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgingReportCompleted(this, new AgingReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit:BankBook", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", ResponseElementName="BankBook_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string BankBook(bool printDetails, bool lineNarration1, bool voucherNaration1, string bankAccNo1, string dateFilter1, string dateFilter2, string dimension1, string dimension2) {
            object[] results = this.Invoke("BankBook", new object[] {
                        printDetails,
                        lineNarration1,
                        voucherNaration1,
                        bankAccNo1,
                        dateFilter1,
                        dateFilter2,
                        dimension1,
                        dimension2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BankBookAsync(bool printDetails, bool lineNarration1, bool voucherNaration1, string bankAccNo1, string dateFilter1, string dateFilter2, string dimension1, string dimension2) {
            this.BankBookAsync(printDetails, lineNarration1, voucherNaration1, bankAccNo1, dateFilter1, dateFilter2, dimension1, dimension2, null);
        }
        
        /// <remarks/>
        public void BankBookAsync(bool printDetails, bool lineNarration1, bool voucherNaration1, string bankAccNo1, string dateFilter1, string dateFilter2, string dimension1, string dimension2, object userState) {
            if ((this.BankBookOperationCompleted == null)) {
                this.BankBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBankBookOperationCompleted);
            }
            this.InvokeAsync("BankBook", new object[] {
                        printDetails,
                        lineNarration1,
                        voucherNaration1,
                        bankAccNo1,
                        dateFilter1,
                        dateFilter2,
                        dimension1,
                        dimension2}, this.BankBookOperationCompleted, userState);
        }
        
        private void OnBankBookOperationCompleted(object arg) {
            if ((this.BankBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BankBookCompleted(this, new BankBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit:CashBook", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", ResponseElementName="CashBook_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CashBook(bool printDetails, bool lineNarration1, bool voucherNaration1, string gLNo1, string dateFilter1, string dateFilter2, string dimension1, string dimension2) {
            object[] results = this.Invoke("CashBook", new object[] {
                        printDetails,
                        lineNarration1,
                        voucherNaration1,
                        gLNo1,
                        dateFilter1,
                        dateFilter2,
                        dimension1,
                        dimension2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CashBookAsync(bool printDetails, bool lineNarration1, bool voucherNaration1, string gLNo1, string dateFilter1, string dateFilter2, string dimension1, string dimension2) {
            this.CashBookAsync(printDetails, lineNarration1, voucherNaration1, gLNo1, dateFilter1, dateFilter2, dimension1, dimension2, null);
        }
        
        /// <remarks/>
        public void CashBookAsync(bool printDetails, bool lineNarration1, bool voucherNaration1, string gLNo1, string dateFilter1, string dateFilter2, string dimension1, string dimension2, object userState) {
            if ((this.CashBookOperationCompleted == null)) {
                this.CashBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCashBookOperationCompleted);
            }
            this.InvokeAsync("CashBook", new object[] {
                        printDetails,
                        lineNarration1,
                        voucherNaration1,
                        gLNo1,
                        dateFilter1,
                        dateFilter2,
                        dimension1,
                        dimension2}, this.CashBookOperationCompleted, userState);
        }
        
        private void OnCashBookOperationCompleted(object arg) {
            if ((this.CashBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CashBookCompleted(this, new CashBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit:CustomerStatement", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", ResponseElementName="CustomerStatement_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CustomerStatement(string customerNo, string startDate, string endDate, bool showOverDueEntries, bool includeAllCustomerWithLedgerEntry, bool includeAllCustomerWithBalance, bool includeReversedEntries, bool includeUnappliedEntries, bool includeAgingBand, string periodLength, int dateChoice, bool logInteraction) {
            object[] results = this.Invoke("CustomerStatement", new object[] {
                        customerNo,
                        startDate,
                        endDate,
                        showOverDueEntries,
                        includeAllCustomerWithLedgerEntry,
                        includeAllCustomerWithBalance,
                        includeReversedEntries,
                        includeUnappliedEntries,
                        includeAgingBand,
                        periodLength,
                        dateChoice,
                        logInteraction});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerStatementAsync(string customerNo, string startDate, string endDate, bool showOverDueEntries, bool includeAllCustomerWithLedgerEntry, bool includeAllCustomerWithBalance, bool includeReversedEntries, bool includeUnappliedEntries, bool includeAgingBand, string periodLength, int dateChoice, bool logInteraction) {
            this.CustomerStatementAsync(customerNo, startDate, endDate, showOverDueEntries, includeAllCustomerWithLedgerEntry, includeAllCustomerWithBalance, includeReversedEntries, includeUnappliedEntries, includeAgingBand, periodLength, dateChoice, logInteraction, null);
        }
        
        /// <remarks/>
        public void CustomerStatementAsync(string customerNo, string startDate, string endDate, bool showOverDueEntries, bool includeAllCustomerWithLedgerEntry, bool includeAllCustomerWithBalance, bool includeReversedEntries, bool includeUnappliedEntries, bool includeAgingBand, string periodLength, int dateChoice, bool logInteraction, object userState) {
            if ((this.CustomerStatementOperationCompleted == null)) {
                this.CustomerStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerStatementOperationCompleted);
            }
            this.InvokeAsync("CustomerStatement", new object[] {
                        customerNo,
                        startDate,
                        endDate,
                        showOverDueEntries,
                        includeAllCustomerWithLedgerEntry,
                        includeAllCustomerWithBalance,
                        includeReversedEntries,
                        includeUnappliedEntries,
                        includeAgingBand,
                        periodLength,
                        dateChoice,
                        logInteraction}, this.CustomerStatementOperationCompleted, userState);
        }
        
        private void OnCustomerStatementOperationCompleted(object arg) {
            if ((this.CustomerStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerStatementCompleted(this, new CustomerStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit:CustomerTrialBalanc" +
            "e", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", ResponseElementName="CustomerTrialBalance_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CustomerTrialBalance(string customerNo1, bool printAmountsInLCY1, bool printOnlyOnePerPage1, bool excludeBalanceOnly1) {
            object[] results = this.Invoke("CustomerTrialBalance", new object[] {
                        customerNo1,
                        printAmountsInLCY1,
                        printOnlyOnePerPage1,
                        excludeBalanceOnly1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerTrialBalanceAsync(string customerNo1, bool printAmountsInLCY1, bool printOnlyOnePerPage1, bool excludeBalanceOnly1) {
            this.CustomerTrialBalanceAsync(customerNo1, printAmountsInLCY1, printOnlyOnePerPage1, excludeBalanceOnly1, null);
        }
        
        /// <remarks/>
        public void CustomerTrialBalanceAsync(string customerNo1, bool printAmountsInLCY1, bool printOnlyOnePerPage1, bool excludeBalanceOnly1, object userState) {
            if ((this.CustomerTrialBalanceOperationCompleted == null)) {
                this.CustomerTrialBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerTrialBalanceOperationCompleted);
            }
            this.InvokeAsync("CustomerTrialBalance", new object[] {
                        customerNo1,
                        printAmountsInLCY1,
                        printOnlyOnePerPage1,
                        excludeBalanceOnly1}, this.CustomerTrialBalanceOperationCompleted, userState);
        }
        
        private void OnCustomerTrialBalanceOperationCompleted(object arg) {
            if ((this.CustomerTrialBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerTrialBalanceCompleted(this, new CustomerTrialBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit:DayBook", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", ResponseElementName="DayBook_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string DayBook(bool lineNarration1, bool voucherNaration1, string documentNo, string postingDate2, string postingDate4, string dimension1, string dimension2) {
            object[] results = this.Invoke("DayBook", new object[] {
                        lineNarration1,
                        voucherNaration1,
                        documentNo,
                        postingDate2,
                        postingDate4,
                        dimension1,
                        dimension2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DayBookAsync(bool lineNarration1, bool voucherNaration1, string documentNo, string postingDate2, string postingDate4, string dimension1, string dimension2) {
            this.DayBookAsync(lineNarration1, voucherNaration1, documentNo, postingDate2, postingDate4, dimension1, dimension2, null);
        }
        
        /// <remarks/>
        public void DayBookAsync(bool lineNarration1, bool voucherNaration1, string documentNo, string postingDate2, string postingDate4, string dimension1, string dimension2, object userState) {
            if ((this.DayBookOperationCompleted == null)) {
                this.DayBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDayBookOperationCompleted);
            }
            this.InvokeAsync("DayBook", new object[] {
                        lineNarration1,
                        voucherNaration1,
                        documentNo,
                        postingDate2,
                        postingDate4,
                        dimension1,
                        dimension2}, this.DayBookOperationCompleted, userState);
        }
        
        private void OnDayBookOperationCompleted(object arg) {
            if ((this.DayBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DayBookCompleted(this, new DayBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit:FeeDemand", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", ResponseElementName="FeeDemand_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FeeDemand(string academicYear, string customerNo, string documentNo) {
            object[] results = this.Invoke("FeeDemand", new object[] {
                        academicYear,
                        customerNo,
                        documentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FeeDemandAsync(string academicYear, string customerNo, string documentNo) {
            this.FeeDemandAsync(academicYear, customerNo, documentNo, null);
        }
        
        /// <remarks/>
        public void FeeDemandAsync(string academicYear, string customerNo, string documentNo, object userState) {
            if ((this.FeeDemandOperationCompleted == null)) {
                this.FeeDemandOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFeeDemandOperationCompleted);
            }
            this.InvokeAsync("FeeDemand", new object[] {
                        academicYear,
                        customerNo,
                        documentNo}, this.FeeDemandOperationCompleted, userState);
        }
        
        private void OnFeeDemandOperationCompleted(object arg) {
            if ((this.FeeDemandCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FeeDemandCompleted(this, new FeeDemandCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit:FeeGeneration", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", ResponseElementName="FeeGeneration_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FeeGeneration(string academicYear, string semester, string feeClassification, string courseCode, string studentNo) {
            object[] results = this.Invoke("FeeGeneration", new object[] {
                        academicYear,
                        semester,
                        feeClassification,
                        courseCode,
                        studentNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FeeGenerationAsync(string academicYear, string semester, string feeClassification, string courseCode, string studentNo) {
            this.FeeGenerationAsync(academicYear, semester, feeClassification, courseCode, studentNo, null);
        }
        
        /// <remarks/>
        public void FeeGenerationAsync(string academicYear, string semester, string feeClassification, string courseCode, string studentNo, object userState) {
            if ((this.FeeGenerationOperationCompleted == null)) {
                this.FeeGenerationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFeeGenerationOperationCompleted);
            }
            this.InvokeAsync("FeeGeneration", new object[] {
                        academicYear,
                        semester,
                        feeClassification,
                        courseCode,
                        studentNo}, this.FeeGenerationOperationCompleted, userState);
        }
        
        private void OnFeeGenerationOperationCompleted(object arg) {
            if ((this.FeeGenerationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FeeGenerationCompleted(this, new FeeGenerationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit:MoneyReceipt", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", ResponseElementName="MoneyReceipt_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string MoneyReceipt(string customerNo, string docNo) {
            object[] results = this.Invoke("MoneyReceipt", new object[] {
                        customerNo,
                        docNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MoneyReceiptAsync(string customerNo, string docNo) {
            this.MoneyReceiptAsync(customerNo, docNo, null);
        }
        
        /// <remarks/>
        public void MoneyReceiptAsync(string customerNo, string docNo, object userState) {
            if ((this.MoneyReceiptOperationCompleted == null)) {
                this.MoneyReceiptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoneyReceiptOperationCompleted);
            }
            this.InvokeAsync("MoneyReceipt", new object[] {
                        customerNo,
                        docNo}, this.MoneyReceiptOperationCompleted, userState);
        }
        
        private void OnMoneyReceiptOperationCompleted(object arg) {
            if ((this.MoneyReceiptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoneyReceiptCompleted(this, new MoneyReceiptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit:PostCautionRefundOr" +
            "der", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", ResponseElementName="PostCautionRefundOrder_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string PostCautionRefundOrder(string entryNo) {
            object[] results = this.Invoke("PostCautionRefundOrder", new object[] {
                        entryNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostCautionRefundOrderAsync(string entryNo) {
            this.PostCautionRefundOrderAsync(entryNo, null);
        }
        
        /// <remarks/>
        public void PostCautionRefundOrderAsync(string entryNo, object userState) {
            if ((this.PostCautionRefundOrderOperationCompleted == null)) {
                this.PostCautionRefundOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostCautionRefundOrderOperationCompleted);
            }
            this.InvokeAsync("PostCautionRefundOrder", new object[] {
                        entryNo}, this.PostCautionRefundOrderOperationCompleted, userState);
        }
        
        private void OnPostCautionRefundOrderOperationCompleted(object arg) {
            if ((this.PostCautionRefundOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostCautionRefundOrderCompleted(this, new PostCautionRefundOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit:PostGeneralPayment", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", ResponseElementName="PostGeneralPayment_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string PostGeneralPayment(string entryNo) {
            object[] results = this.Invoke("PostGeneralPayment", new object[] {
                        entryNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostGeneralPaymentAsync(string entryNo) {
            this.PostGeneralPaymentAsync(entryNo, null);
        }
        
        /// <remarks/>
        public void PostGeneralPaymentAsync(string entryNo, object userState) {
            if ((this.PostGeneralPaymentOperationCompleted == null)) {
                this.PostGeneralPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostGeneralPaymentOperationCompleted);
            }
            this.InvokeAsync("PostGeneralPayment", new object[] {
                        entryNo}, this.PostGeneralPaymentOperationCompleted, userState);
        }
        
        private void OnPostGeneralPaymentOperationCompleted(object arg) {
            if ((this.PostGeneralPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostGeneralPaymentCompleted(this, new PostGeneralPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit:PostStudentFeeColle" +
            "ction", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", ResponseElementName="PostStudentFeeCollection_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/FeeManagementCodeUnit", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string PostStudentFeeCollection(string entryNo) {
            object[] results = this.Invoke("PostStudentFeeCollection", new object[] {
                        entryNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostStudentFeeCollectionAsync(string entryNo) {
            this.PostStudentFeeCollectionAsync(entryNo, null);
        }
        
        /// <remarks/>
        public void PostStudentFeeCollectionAsync(string entryNo, object userState) {
            if ((this.PostStudentFeeCollectionOperationCompleted == null)) {
                this.PostStudentFeeCollectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostStudentFeeCollectionOperationCompleted);
            }
            this.InvokeAsync("PostStudentFeeCollection", new object[] {
                        entryNo}, this.PostStudentFeeCollectionOperationCompleted, userState);
        }
        
        private void OnPostStudentFeeCollectionOperationCompleted(object arg) {
            if ((this.PostStudentFeeCollectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostStudentFeeCollectionCompleted(this, new PostStudentFeeCollectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AgingReportCompletedEventHandler(object sender, AgingReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgingReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgingReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void BankBookCompletedEventHandler(object sender, BankBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BankBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BankBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CashBookCompletedEventHandler(object sender, CashBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CashBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CashBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CustomerStatementCompletedEventHandler(object sender, CustomerStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CustomerTrialBalanceCompletedEventHandler(object sender, CustomerTrialBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerTrialBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerTrialBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DayBookCompletedEventHandler(object sender, DayBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DayBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DayBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FeeDemandCompletedEventHandler(object sender, FeeDemandCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FeeDemandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FeeDemandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FeeGenerationCompletedEventHandler(object sender, FeeGenerationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FeeGenerationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FeeGenerationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void MoneyReceiptCompletedEventHandler(object sender, MoneyReceiptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MoneyReceiptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MoneyReceiptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PostCautionRefundOrderCompletedEventHandler(object sender, PostCautionRefundOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostCautionRefundOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostCautionRefundOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PostGeneralPaymentCompletedEventHandler(object sender, PostGeneralPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostGeneralPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostGeneralPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PostStudentFeeCollectionCompletedEventHandler(object sender, PostStudentFeeCollectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostStudentFeeCollectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostStudentFeeCollectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591